name: Basic

on: push

jobs:
  job-one:
    name: Introduction
    runs-on: ubuntu-latest

    steps:
      - name: Print some text
        run: echo Hello
      - name: ASCII text
        uses: mscoutermarsh/ascii-art-action@master
        with:
          text: 'SHIP IT'
