# name: Basic

# on: push

# jobs:
#   job-one:
#     name: Introduction
#     runs-on: ubuntu-latest

#     steps:
#       - name: Print some text
#         run: echo Hello
#       - name: ASCII text
#         uses: mscoutermarsh/ascii-art-action@master
#         with:
#           text: 'SHIP IT'

# run the script
# run some tests
# make entire code base pep compliant

name: Python example

on: push #pull requests, push(on a specific branch), cron job or something manual

jobs:
  build:
    runs-on: ubuntu-latest # windows, mac-os
    name: Python script
    steps:
      - uses: actions/checkout@v2 # load our repository to the ubuntu machine on github
      - name: Python Setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Installation of packages
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          pip install -U scikit-learn
          pip install pytest
      - name: Run Script
        run: |
          python script.py
      - name: Run Tests
        run: |
          pytest test.py
